package org.mpisws.sddrservice.lib;

import android.os.ParcelUuid;

/**
 * 
 * @author verdelyi
 */
public class Constants {
    /**
     * UUID identified with this app - randomly generated by uuidgen
     */
    public static final ParcelUuid SDDR_UUID = ParcelUuid
            .fromString("39623898-d12c-4787-8dd7-53ae7c06f1ea");

    public static final int REQUEST_ENABLE_BT = 1;
    public static final int REQUEST_ACCESS_FINE_LOCATION = 2;

    /**
     * Advertising-related constants
     */
    public static final int TOTAL_LENGTH = 31;
    public static final int PUUID_LENGTH = 16;
    public static final int ADDR_LENGTH = 3;
    public static final int ADVERT_LENGTH = TOTAL_LENGTH-PUUID_LENGTH-6;

    /**
     * Scanning-related constants
     */
    public static final long SCAN_PERIOD = 700;

    /**
     * Other Constants
     */
    public static final android.icu.text.SimpleDateFormat fullTimeFormat = new android.icu.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    public static final int HANDSHAKE_DH_SIZE = 24;
}
