/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mpisws_fog_ebncore_EbNCoreNative */

#ifndef _Included_org_mpisws_fog_ebncore_EbNCoreNative
#define _Included_org_mpisws_fog_ebncore_EbNCoreNative
#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT jint JNICALL JNI_OnLoad
  (JavaVM *vm, void *reserved);

/*
 * Class:     org_mpisws_fog_ebncore_EbNCoreNative
 * Method:    startNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_mpisws_fog_ebncore_EbNCoreNative_startNative
  (JNIEnv *, jobject);

/*
 * Class:     org_mpisws_fog_ebncore_EbNCoreNative
 * Method:    stopNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_mpisws_fog_ebncore_EbNCoreNative_stopNative
  (JNIEnv *, jobject);

/*
 * Class:     org_mpisws_fog_ebncore_EbNCoreNative
 * Method:    updateLinkability
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_org_mpisws_fog_ebncore_EbNCoreNative_updateLinkability
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
