/* DO NOT EDIT THIS FILE - it is machine generated */
#include "include/SDDRRadio.h"
#include "include/Config.h"
#include <jni.h>
/* Header for class org_mpisws_sddrservice_encounters_SDDR_Native */

#ifndef _Included_org_mpisws_sddrservice_encounters_SDDR_Native
#define _Included_org_mpisws_sddrservice_encounters_SDDR_Native
#ifdef __cplusplus
extern "C" {
#endif
#undef org_mpisws_sddrservice_encounters_SDDR_Native_BIND_ABOVE_CLIENT
#define org_mpisws_sddrservice_encounters_SDDR_Native_BIND_ABOVE_CLIENT 8L
#undef org_mpisws_sddrservice_encounters_SDDR_Native_BIND_ADJUST_WITH_ACTIVITY
#define org_mpisws_sddrservice_encounters_SDDR_Native_BIND_ADJUST_WITH_ACTIVITY 128L
#undef org_mpisws_sddrservice_encounters_SDDR_Native_BIND_ALLOW_OOM_MANAGEMENT
#define org_mpisws_sddrservice_encounters_SDDR_Native_BIND_ALLOW_OOM_MANAGEMENT 16L
#undef org_mpisws_sddrservice_encounters_SDDR_Native_BIND_AUTO_CREATE
#define org_mpisws_sddrservice_encounters_SDDR_Native_BIND_AUTO_CREATE 1L
#undef org_mpisws_sddrservice_encounters_SDDR_Native_BIND_DEBUG_UNBIND
#define org_mpisws_sddrservice_encounters_SDDR_Native_BIND_DEBUG_UNBIND 2L
#undef org_mpisws_sddrservice_encounters_SDDR_Native_BIND_EXTERNAL_SERVICE
#define org_mpisws_sddrservice_encounters_SDDR_Native_BIND_EXTERNAL_SERVICE -2147483648L
#undef org_mpisws_sddrservice_encounters_SDDR_Native_BIND_IMPORTANT
#define org_mpisws_sddrservice_encounters_SDDR_Native_BIND_IMPORTANT 64L
#undef org_mpisws_sddrservice_encounters_SDDR_Native_BIND_NOT_FOREGROUND
#define org_mpisws_sddrservice_encounters_SDDR_Native_BIND_NOT_FOREGROUND 4L
#undef org_mpisws_sddrservice_encounters_SDDR_Native_BIND_WAIVE_PRIORITY
#define org_mpisws_sddrservice_encounters_SDDR_Native_BIND_WAIVE_PRIORITY 32L
#undef org_mpisws_sddrservice_encounters_SDDR_Native_CONTEXT_IGNORE_SECURITY
#define org_mpisws_sddrservice_encounters_SDDR_Native_CONTEXT_IGNORE_SECURITY 2L
#undef org_mpisws_sddrservice_encounters_SDDR_Native_CONTEXT_INCLUDE_CODE
#define org_mpisws_sddrservice_encounters_SDDR_Native_CONTEXT_INCLUDE_CODE 1L
#undef org_mpisws_sddrservice_encounters_SDDR_Native_CONTEXT_RESTRICTED
#define org_mpisws_sddrservice_encounters_SDDR_Native_CONTEXT_RESTRICTED 4L
#undef org_mpisws_sddrservice_encounters_SDDR_Native_MODE_APPEND
#define org_mpisws_sddrservice_encounters_SDDR_Native_MODE_APPEND 32768L
#undef org_mpisws_sddrservice_encounters_SDDR_Native_MODE_ENABLE_WRITE_AHEAD_LOGGING
#define org_mpisws_sddrservice_encounters_SDDR_Native_MODE_ENABLE_WRITE_AHEAD_LOGGING 8L
#undef org_mpisws_sddrservice_encounters_SDDR_Native_MODE_MULTI_PROCESS
#define org_mpisws_sddrservice_encounters_SDDR_Native_MODE_MULTI_PROCESS 4L
#undef org_mpisws_sddrservice_encounters_SDDR_Native_MODE_NO_LOCALIZED_COLLATORS
#define org_mpisws_sddrservice_encounters_SDDR_Native_MODE_NO_LOCALIZED_COLLATORS 16L
#undef org_mpisws_sddrservice_encounters_SDDR_Native_MODE_PRIVATE
#define org_mpisws_sddrservice_encounters_SDDR_Native_MODE_PRIVATE 0L
#undef org_mpisws_sddrservice_encounters_SDDR_Native_MODE_WORLD_READABLE
#define org_mpisws_sddrservice_encounters_SDDR_Native_MODE_WORLD_READABLE 1L
#undef org_mpisws_sddrservice_encounters_SDDR_Native_MODE_WORLD_WRITEABLE
#define org_mpisws_sddrservice_encounters_SDDR_Native_MODE_WORLD_WRITEABLE 2L
#undef org_mpisws_sddrservice_encounters_SDDR_Native_RECEIVER_VISIBLE_TO_INSTANT_APPS
#define org_mpisws_sddrservice_encounters_SDDR_Native_RECEIVER_VISIBLE_TO_INSTANT_APPS 1L
#undef org_mpisws_sddrservice_encounters_SDDR_Native_START_CONTINUATION_MASK
#define org_mpisws_sddrservice_encounters_SDDR_Native_START_CONTINUATION_MASK 15L
#undef org_mpisws_sddrservice_encounters_SDDR_Native_START_FLAG_REDELIVERY
#define org_mpisws_sddrservice_encounters_SDDR_Native_START_FLAG_REDELIVERY 1L
#undef org_mpisws_sddrservice_encounters_SDDR_Native_START_FLAG_RETRY
#define org_mpisws_sddrservice_encounters_SDDR_Native_START_FLAG_RETRY 2L
#undef org_mpisws_sddrservice_encounters_SDDR_Native_START_NOT_STICKY
#define org_mpisws_sddrservice_encounters_SDDR_Native_START_NOT_STICKY 2L
#undef org_mpisws_sddrservice_encounters_SDDR_Native_START_REDELIVER_INTENT
#define org_mpisws_sddrservice_encounters_SDDR_Native_START_REDELIVER_INTENT 3L
#undef org_mpisws_sddrservice_encounters_SDDR_Native_START_STICKY
#define org_mpisws_sddrservice_encounters_SDDR_Native_START_STICKY 1L
#undef org_mpisws_sddrservice_encounters_SDDR_Native_START_STICKY_COMPATIBILITY
#define org_mpisws_sddrservice_encounters_SDDR_Native_START_STICKY_COMPATIBILITY 0L
#undef org_mpisws_sddrservice_encounters_SDDR_Native_STOP_FOREGROUND_DETACH
#define org_mpisws_sddrservice_encounters_SDDR_Native_STOP_FOREGROUND_DETACH 2L
#undef org_mpisws_sddrservice_encounters_SDDR_Native_STOP_FOREGROUND_REMOVE
#define org_mpisws_sddrservice_encounters_SDDR_Native_STOP_FOREGROUND_REMOVE 1L

/*
 * Class:     org_mpisws_sddrservice_encounters_SDDR_Native
 * Method:    c_mallocRadio
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_mpisws_sddrservice_encounters_SDDR_1Native_c_1mallocRadio
  (JNIEnv *, jobject);

/*
 * Class:     org_mpisws_sddrservice_encounters_SDDR_Native
 * Method:    c_freeRadio
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_mpisws_sddrservice_encounters_SDDR_1Native_c_1freeRadio
  (JNIEnv *, jobject);

/*
 * Class:     org_mpisws_sddrservice_encounters_SDDR_Native
 * Method:    c_getNextRadioAction
 * Signature: ()L
 */
JNIEXPORT jobject JNICALL Java_org_mpisws_sddrservice_encounters_SDDR_1Native_c_1getNextRadioAction
  (JNIEnv *, jobject);

/*
 * Class:     org_mpisws_sddrservice_encounters_SDDR_Native
 * Method:    c_changeEpoch
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_mpisws_sddrservice_encounters_SDDR_1Native_c_1changeEpoch
  (JNIEnv *, jobject);

/*
 * Class:     org_mpisws_sddrservice_encounters_SDDR_Native
 * Method:    c_getRandomAddr
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_mpisws_sddrservice_encounters_SDDR_1Native_c_1getRandomAddr
  (JNIEnv *, jobject);

/* From class org_mpisws_sddrservice_encounters_SDDR_1Native */

#undef org_mpisws_sddrservice_encounters_SDDR_1Native_SCAN_PERIOD
#define org_mpisws_sddrservice_encounters_SDDR_1Native_SCAN_PERIOD 1500LL
/*
 * Class:     org_mpisws_sddrservice_encounters_SDDR_1Native
 * Method:    c_processScanResult
 * Signature: ([BI[B)V
 */
JNIEXPORT jboolean JNICALL Java_org_mpisws_sddrservice_encounters_SDDR_1Native_c_1processScanResult
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray);

/*
 * Class:     org_mpisws_sddrservice_encounters_SDDR_1Native
 * Method:    c_preDiscovery
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_mpisws_sddrservice_encounters_SDDR_1Native_c_1preDiscovery
  (JNIEnv *, jobject);

/*
 * Class:     org_mpisws_sddrservice_encounters_SDDR_1Native
 * Method:    c_postDiscovery
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_mpisws_sddrservice_encounters_SDDR_1Native_c_1postDiscovery
  (JNIEnv *, jobject);

JNIEXPORT jbyteArray JNICALL Java_org_mpisws_sddrservice_encounters_SDDR_1Native_c_1getMyDHKey(JNIEnv *env, jobject obj);

JNIEXPORT jbyteArray JNICALL Java_org_mpisws_sddrservice_encounters_SDDR_1Native_c_1getMyAdvert(JNIEnv *env, jobject obj);

#ifdef __cplusplus
}
#endif
#endif
